#' @return A shinyUI
#' @export
#app.ui <- function(){
library(shiny)
library(plotly)
library(shinydashboard)
library(shinycssloaders)
library(colourpicker)
library(shinyFiles)
library(readr)
library(shinyjqui)

shinyUI( dashboardPage(skin = "black",
                       dashboardHeader(title="SpikeIt"),
                       
                       dashboardSidebar(
                         sidebarMenu(id="menu",
                                     menuItem("Setup", tabName="setup", badgeLabel=uiOutput("badgeText_samples"), badgeColor="blue"),
                                     menuItem("Plot Curves", tabName="plot"),
                                     menuItem("Spike Analyzer", tabName="spike"),
                                     menuItem("Export", tabName="export"),
                                     menuItem("About", tabName="about")
                         )
                       ),
                       dashboardBody(
                         tabItems(
                         tabItem("setup",
                                 box(width=6, title = "Samples", actionButton("removesamples", "remove all"),actionButton("testsamples", "load example"), tableOutput("samples_info")),
                                 box(width=6, title = "Setup",
                                     fileInput("sampleFileInput",label="Select trace-tables generated by the Spike Analyzer Plugin", multiple=T)),
                                 box(width=12, selectInput("preview_sample", "Table Preview", choices=c(), selectize=F),
                                     uiOutput("column"),
                                     DT::dataTableOutput("tabs")
                                 )
                                 
                                 
                         ),
                         
                       tabItem("plot",
                               
                               box(width=6,  height = "100%", title = "Plot Calcium Traces",
                                   
                                   selectInput("view_sample", "Select a Table", choices=c(), selectize=F, multiple = F),
                                   uiOutput("plotcolumn", width=6), uiOutput("cells", width=6),
                                   #uiOutput("background", width=6),
                                   numericInput("del", "Time between Frames (in ms)", value = 100, min = 0, max = 10000),
                                   sliderInput("stringency", "Choose a stringency for the peak detection", 0, 100, step=0.1, value=5),
                                   sliderInput("dfThresh", "Choose a minimum dF/F threshold value", 0, 5, step=0.01, value=0.1),
                                   checkboxInput("checkFacetgrid", "Use a facet_grids", value = F),
                                   checkboxInput("show.peaks", "Show Peak Points (Start in Red, End in Blue)", value = F)),
                               box(width=6, height = "100%", title = "Plot Calcium Traces",
                                   jqui_resizable(plotOutput("traces",  width = "100%",  height = "100%"))
                                   ),
                               
                               box(width=12, collapsed=T, collapsible = T, title="Plot Parameters",
                                   sliderInput("plotWidth", "Plot-Width in cm", 1, 50, step=0.5, value=8),
                                   sliderInput("plotHeight", "Plot-Height in cm", 1, 50, step=0.5, value=11),
                               downloadButton("downloadPlot", "Download"))
                               
                               
                               ),
                       
                       tabItem("spike",
                               
                               box(width=12, title = "Setup Parameters",
                                   
                                   uiOutput("plotcolumn2", width=6),
                                   #uiOutput("background2", width=6),
                                   numericInput("del2", "Time between Frames (in ms)", value = 100, min = 0, max = 10000),
                                   sliderInput("stringency2", "Choose a stringency for the peak detection", 0, 100, step=0.1, value=5),
                                   sliderInput("dfThresh2", "Choose a minimum dF/F threshold value", 0, 5, step=0.01, value=0.1),
                                   actionButton("analysis", "Start Analysis")
                                   ),
                               box(width=12, collapsed=T, collapsible = T, title="Inspect Tables",
                                   #checkboxInput("checkFacetgrid", "Use a facet_grids", value = F),
                                   selectInput("resultsTable", "Select a Table", choices=list("Peak-wise"="peakTables", "Cell-wise"="meanTables"), selectize=F, multiple = F),
                                   DT::dataTableOutput("results")),
                               box(width=12, collapsed=T, collapsible = T, title="Plot Results",

                                   selectizeInput("resultsColumns", "Select which Parameters to Plot", choices=c("Peak.Time", "Peak.Intensity","Peak.Start", "Peak.Stop", "Start.Intensity", "Stop.Intensity", 
                                                                                                                 "Peak.Duration", "Duration.To.Peak", "Time.To.Decay", "Baseline.Intensity", "Amplitude")
                                                  , selected="Amplitude",  multiple=T),
                                   
                                   jqui_resizable(plotOutput("plotResults"))
                                   )
                               ),
                       tabItem("export",
                               
                               box(width=12, title="Export Data Tables",
                                   
                                   textInput("tabTitle", "Save as ", "Peak-Tables"),
                                   
                                   selectInput("download_table", "Select a Table", choices=list("Peak-wise"="peakTables", "Cell-wise"="meanTables"), selectize=F, multiple = F),
                                   
                                   downloadButton("downloadTable", "Download Table")
                                   
                                   )
                               
                               
                               
                               )
                               
                               
                       )
                         
                         
                         
                         
                         
                       ))
)
#}
